// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs).
// The Rust source of truth lives in `src/web/session.rs::Capability`.

/**
 * An optional part of the contract a session offers.
 *
 * Read from `SessionResponse.capabilities` rather than probing endpoints: a
 * 404 on a capability that was never advertised is not a useful runtime error.
 */
export type Capability =
    /** `GET /api/v1/theme.css` is served; the frontend should link it. */
    | "theme"
    /** `POST /api/v1/save` writes a draft that outlives the process. */
    | "draft";
