// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs).
// The Rust source of truth lives in `src/web/session.rs::SessionResponse` and `Capability`.
// Manually maintained to add human-readable doc comments; regenerate with
// `cargo test --features web-types` and re-apply comments when the struct changes.

import type { Capability } from "./Capability";
import type { RichAsset } from "./RichAsset";

export interface SessionResponse {
    /** Contract revision this payload follows, e.g. "1.0". */
    api_version: string;
    /** Optional endpoints this session actually serves. Check before calling them. */
    capabilities: Array<Capability>;
    title: string | null;
    description: string | null;
    // Raw UiAst tree from the backend; the web UI wraps this into its own
    // UiAst type in `web/ui/src/types.ts`.
    ui_ast: Record<string, unknown>;
    data: Record<string, unknown>;
    formats: Array<string>;
    // Optional UiLayout tree; the web UI also reinterprets this locally.
    layout: Record<string, unknown> | null;
    // Rendered rich content keyed by content id: the lookup table for every
    // figure and prose block the AST declares (`x-content`, `x-options`).
    // Absent when the schema declared nothing or this build renders none of
    // the declared kinds; frontends fall back to showing the source.
    rich?: Record<string, RichAsset> | null;
    // Milliseconds until the backend aborts the session, or null when the
    // session is unbounded. A duration, not a deadline, so a client whose clock
    // is off still counts down correctly. The client owns the visible countdown
    // because the server stops answering once the deadline passes.
    expires_in_ms: number | null;
    /** True when the initial `data` came from a saved draft rather than the caller. */
    draft_restored: boolean;
}
